// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.12.1
// source: proto/productpb/product.proto

package productpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProductPriceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
}

func (x *ProductPriceRequest) Reset() {
	*x = ProductPriceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productpb_product_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceRequest) ProtoMessage() {}

func (x *ProductPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productpb_product_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceRequest.ProtoReflect.Descriptor instead.
func (*ProductPriceRequest) Descriptor() ([]byte, []int) {
	return file_proto_productpb_product_proto_rawDescGZIP(), []int{0}
}

func (x *ProductPriceRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type ProductPriceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ValueInCents int64 `protobuf:"varint,1,opt,name=value_in_cents,json=valueInCents,proto3" json:"value_in_cents,omitempty"`
}

func (x *ProductPriceResponse) Reset() {
	*x = ProductPriceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_productpb_product_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProductPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductPriceResponse) ProtoMessage() {}

func (x *ProductPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_productpb_product_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductPriceResponse.ProtoReflect.Descriptor instead.
func (*ProductPriceResponse) Descriptor() ([]byte, []int) {
	return file_proto_productpb_product_proto_rawDescGZIP(), []int{1}
}

func (x *ProductPriceResponse) GetValueInCents() int64 {
	if x != nil {
		return x.ValueInCents
	}
	return 0
}

var File_proto_productpb_product_proto protoreflect.FileDescriptor

var file_proto_productpb_product_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70,
	0x62, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x22, 0x34, 0x0a,
	0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x49, 0x64, 0x22, 0x3c, 0x0a, 0x14, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x69, 0x6e, 0x5f, 0x63, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x49, 0x6e, 0x43, 0x65, 0x6e, 0x74,
	0x73, 0x32, 0x6a, 0x0a, 0x13, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x08, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x4f, 0x6e, 0x65, 0x12, 0x21, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a,
	0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_productpb_product_proto_rawDescOnce sync.Once
	file_proto_productpb_product_proto_rawDescData = file_proto_productpb_product_proto_rawDesc
)

func file_proto_productpb_product_proto_rawDescGZIP() []byte {
	file_proto_productpb_product_proto_rawDescOnce.Do(func() {
		file_proto_productpb_product_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_productpb_product_proto_rawDescData)
	})
	return file_proto_productpb_product_proto_rawDescData
}

var file_proto_productpb_product_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_productpb_product_proto_goTypes = []interface{}{
	(*ProductPriceRequest)(nil),  // 0: grpc.product.ProductPriceRequest
	(*ProductPriceResponse)(nil), // 1: grpc.product.ProductPriceResponse
}
var file_proto_productpb_product_proto_depIdxs = []int32{
	0, // 0: grpc.product.ProductPriceService.FetchOne:input_type -> grpc.product.ProductPriceRequest
	1, // 1: grpc.product.ProductPriceService.FetchOne:output_type -> grpc.product.ProductPriceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_productpb_product_proto_init() }
func file_proto_productpb_product_proto_init() {
	if File_proto_productpb_product_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_productpb_product_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductPriceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_productpb_product_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProductPriceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_productpb_product_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_productpb_product_proto_goTypes,
		DependencyIndexes: file_proto_productpb_product_proto_depIdxs,
		MessageInfos:      file_proto_productpb_product_proto_msgTypes,
	}.Build()
	File_proto_productpb_product_proto = out.File
	file_proto_productpb_product_proto_rawDesc = nil
	file_proto_productpb_product_proto_goTypes = nil
	file_proto_productpb_product_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProductPriceServiceClient is the client API for ProductPriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProductPriceServiceClient interface {
	FetchOne(ctx context.Context, in *ProductPriceRequest, opts ...grpc.CallOption) (*ProductPriceResponse, error)
}

type productPriceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProductPriceServiceClient(cc grpc.ClientConnInterface) ProductPriceServiceClient {
	return &productPriceServiceClient{cc}
}

func (c *productPriceServiceClient) FetchOne(ctx context.Context, in *ProductPriceRequest, opts ...grpc.CallOption) (*ProductPriceResponse, error) {
	out := new(ProductPriceResponse)
	err := c.cc.Invoke(ctx, "/grpc.product.ProductPriceService/FetchOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductPriceServiceServer is the server API for ProductPriceService service.
type ProductPriceServiceServer interface {
	FetchOne(context.Context, *ProductPriceRequest) (*ProductPriceResponse, error)
}

// UnimplementedProductPriceServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProductPriceServiceServer struct {
}

func (*UnimplementedProductPriceServiceServer) FetchOne(context.Context, *ProductPriceRequest) (*ProductPriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchOne not implemented")
}

func RegisterProductPriceServiceServer(s *grpc.Server, srv ProductPriceServiceServer) {
	s.RegisterService(&_ProductPriceService_serviceDesc, srv)
}

func _ProductPriceService_FetchOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProductPriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductPriceServiceServer).FetchOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpc.product.ProductPriceService/FetchOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductPriceServiceServer).FetchOne(ctx, req.(*ProductPriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProductPriceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.product.ProductPriceService",
	HandlerType: (*ProductPriceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchOne",
			Handler:    _ProductPriceService_FetchOne_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/productpb/product.proto",
}
